### ISSUE TITLE
Requesting take down of this repository

### ISSUE THREAD

**Issue by WolfgangSenff** [Overvault-64/Firebase-Godot-API#1]
You've infringed the copyright of the original repository (found here: https://github.com/GodotNuts/GodotFirebase) by simply copying the entire repository, removing several notes of authorship on top of most files, changing a few function and signal names, adding one very small feature that we would have preferred you simply open a PR for against our repository (and would have been accepted with credit to you!), and calling it your own, including the copyright, which does not belong to you for the vast majority of files in this repository. Your use does not fall under the "fair use" policy, so I have to kindly ask you to take this repository down and remove your plugin from the Godot asset library.

In the future, if you intend to do something similar with other popular plugins, I recommend you at least include a reference back to the original plugin in your Godot asset library description. The way you have it makes it very clear you were just trying to take advantage of our work and name (even referring to our wiki for a guide!) without providing very much useful, unique code.

**Comment by Overvault-64** [comment]
Ok let me recap.
In [september 2022](https://github.com/GodotNuts/GodotFirebase/discussions/311) I was said that you weren't planning to port your 3.x library to 4, so I made it instead.

In the process, I debugged and tested the entire library and discovered, a part from a quantity of bugs and inconsistencies, that whole parts of it were known to be broken and untested (e.g. the whole cache management), even in the releases. I was in contact with fenix, who also confirmed this fact.

For this reason, combined with the fact that I had already changed the library initialization method (and disagreed with your architecture choices), I decided to rework the library structure from ground up. I think even an idiot would understand that I removed nothing, but simply created new scripts and copied the functions I ported and rewrote from your 3.x library.

When I was done, the structure of my library was incompatible with yours, so I informed my only contact that I was distributing my library in a new repo (use google translate)
![image](https://user-images.githubusercontent.com/96829602/231553250-da9f25c2-f8e2-4996-bd21-6959dba45135.png)

<br>

Now you show up and accuse me of theft. 
> you were just trying to take advantage of our work and name (even referring to our wiki for a guide!)

<br>

I like to imagine you reading [this part](https://github.com/Overvault-64/Firebase-for-Godot-4.x#differences-with-godotfirebase) of my README
>Differences with GodotFirebase
Despite a slightly different architecture, Firebase API 4.x inherited most of the original methods and signals, so you can refer to the original [wiki](https://github.com/GodotNuts/GodotFirebase/wiki) for guidance.

and thinking "HEY! This guy is stealing our work! He's calling it his own!". Lol.

<br>

Talking about back-references and attributions, which you accuse me of not including, let me quote [line 28](https://github.com/Overvault-64/Firebase-for-Godot-4.x/blob/main/README.md) of my readme, which you wilfully ignored:
> Unlike [GodotFirebase](https://github.com/GodotNuts/GodotFirebase), on which this library is based

<br>

To be clear, I won't take down anything, since I broke no copyright whatsoever.
I will just restore your name in the license, so that people know that I've been working for weeks to fix your thing.

<br>

Btw, since my library is released under MIT license (like yours, but you may not know that) feel free to copy-paste my code over yours. It's fully working and tested. I will not hurl senseless accusations at you, I promise!

<br>

Have a nice day! 👋

**Comment by Overvault-64** [comment]
Ok let me recap.
In [september 2022](https://github.com/GodotNuts/GodotFirebase/discussions/311) I was said that you weren't planning to port your 3.x library to 4, so I made it instead.

In the process, I debugged and tested the entire library and discovered, a part from a quantity of bugs and inconsistencies, that whole parts of it were known to be broken and untested (e.g. the whole cache management), even in the releases. I was in contact with fenix, who also confirmed this fact.

For this reason, combined with the fact that I had already changed the library initialization method (and disagreed with your architecture choices), I decided to rework the library structure from ground up. I think even an idiot would understand that I removed nothing, but simply created new scripts and copied the functions I ported and rewrote from your 3.x library.

When I was done, the structure of my library was incompatible with yours, so I informed my only contact that I was distributing my library in a new repo (use google translate)
![image](https://user-images.githubusercontent.com/96829602/231553250-da9f25c2-f8e2-4996-bd21-6959dba45135.png)

<br>

Now you show up and accuse me of theft. 
> you were just trying to take advantage of our work and name (even referring to our wiki for a guide!)

<br>

I like to imagine you reading [this part](https://github.com/Overvault-64/Firebase-for-Godot-4.x#differences-with-godotfirebase) of my README
>Differences with GodotFirebase
Despite a slightly different architecture, Firebase API 4.x inherited most of the original methods and signals, so you can refer to the original [wiki](https://github.com/GodotNuts/GodotFirebase/wiki) for guidance.

and thinking "HEY! This guy is stealing our work! He's calling it his own!". Lol.

<br>

Talking about back-references and attributions, which you accuse me of not including, let me quote [line 28](https://github.com/Overvault-64/Firebase-for-Godot-4.x/blob/main/README.md) of my readme, which you wilfully ignored:
> Unlike [GodotFirebase](https://github.com/GodotNuts/GodotFirebase), on which this library is based

<br>

To be clear, I won't take down anything, since I broke no copyright whatsoever.
I will just restore your name in the license, so that people know that I've been working for weeks to fix your thing.

<br>

Btw, since my library is released under MIT license (like yours, but you may not know that) feel free to copy-paste my code over yours. It's fully working and tested. I will not hurl senseless accusations at you, I promise!

<br>

Have a nice day! 👋
