### ISSUE TITLE
How to get data from Realtime Database reference

### ISSUE THREAD

**Issue by JapanYoshi** [Overvault-64/Firebase-Godot-API#2]
I've looked at the Readme, I've looked at the Wiki it lead to, and I've looked at the code for reference.gd, but I just can't find out how to get the value pointed by a reference in Firebase Realtime Database.

For the sake of example, say that my Realtime Database looks like this:

    {
      roomCodes: {
        "AAAA": true,
        "ABCD": true,
        "TEST": false
      },
      globalEvent: false
    }

And my GDScript code looks like this:

    func get_room_code_list():
      # Assume that I'm already authorized
      var room_list_ref: RealtimeReference =\
        Firebase.Realtime.get_realtime_reference("roomCodes")
      ?????
      return ?????

What do I do to make the function return `{"AAAA": true, "ABCD": true, "TEST": false}`?

**Comment by Overvault-64** [comment]
Assuming that, as you said, you already connected to the database, you create the realtime reference and connect its `new_data_update` signal to another function. The signal will fire every time there's an update in that branch of your database and have as argument the updated data.

```
func _ready():
    var ref = Firebase.Realtime.get_realtime_reference("roomCodes")
    ref.new_data_update.connect(myfunc)

func myfunc(update):
    print(update.data)
```

**Comment by Overvault-64** [comment]
Then you don't need a realtime reference. That's for getting realtime updates.
Just make a http request.
```
var http := HTTPRequest.new()
add_child(http)
http.request("https://your-database-url/roomCodes.json")
var response = await http.request_completed #or connect it to a function
var content = response[3].get_string_from_utf8()
```

**Comment by JapanYoshi** [comment]
Holy SHIT that's janky. You can set up a reference to get signals when the value changes, but you can't get the value that it currently is, i.e. what it's supposed to change *from?*

For the record, the repo that you're basing this repo on has [an Issue that says he's working on this very feature](https://github.com/GodotNuts/GodotFirebase/issues/365) because it's a legitimate function with a legitimate use case.

**Comment by Overvault-64** [comment]
>You can set up a reference to get signals when the value changes, but you can't get the value that it currently is

Correct, there's no built-in method for it.

>it's a legitimate function with a legitimate use case

I agree.

>And it didn't even work

Actually, it worked. The request returned a permission denied error because your database is protected by authentication.

That `HTTPRequest` object has no connection with the plugin nor your configuration, so sending the request without any headers is the equivalent of entering `https://your-database-url/roomCodes.json` in a random unauthenticated browser tab.

If you want to authenticate your requests, you'll have to save your auth token somewhere when authenticating with the plugin and then passing them with your request.

It should work like the following but I currently have no test environment in place so feel free to test it for yourself.

```
var token = "your_previously_saved_token"
var headers = [
        "Content-Type: application/json",
        "Authorization: Bearer " + token
      ]
http.request("https://your-database-url/roomCodes.json", headers)
```

<br>

>Holy SHIT that's janky

You're welcome

**Comment by Overvault-64** [comment]
>You can set up a reference to get signals when the value changes, but you can't get the value that it currently is

Correct, there's no built-in method for it.

>it's a legitimate function with a legitimate use case

I agree.

>And it didn't even work

Actually, it worked. The request returned a permission denied error because your database is protected by authentication and you're not authenticating your request. That's quite obvious.

That `HTTPRequest` object has no connection with the plugin nor your configuration, so sending the request without any headers is the equivalent of entering `https://your-database-url/roomCodes.json` in a random unauthenticated browser tab.

You'll have to save your auth token somewhere when authenticating with the plugin and then pass it with your request.

It should work like the following but I currently have no test environment in place so feel free to test it for yourself.

```
var token = "your_previously_saved_token"
var headers = [
        "Content-Type: application/json",
        "Authorization: Bearer " + token
      ]
http.request("https://your-database-url/roomCodes.json", headers)
```

<br>

>Holy SHIT that's janky

You're welcome

**Comment by JapanYoshi** [comment]
> Actually, it worked. The request returned a permission denied error because your database is protected by authentication and you're not authenticating your request. That's quite obvious.
> 
> That `HTTPRequest` object has no connection with the plugin nor your configuration, so sending the request without any headers is the equivalent of entering `https://your-database-url/roomCodes.json` in a random unauthenticated browser tab.
> 
> You'll have to save your auth token somewhere when authenticating with the plugin and then pass it with your request.
> 
> It should work like the following but I currently have no test environment in place so feel free to test it for yourself.
> 
> ```
> var token = "your_previously_saved_token"
> var headers = [
>         "Content-Type: application/json",
>         "Authorization: Bearer " + token
>       ]
> http.request("https://your-database-url/roomCodes.json", headers)
> ```

Nope. Here's the response that the auth request gave me.

    {
      "kind": "identitytoolkit#SignupNewUserResponse",
      "idtoken": "*845 characters*",
      "refreshtoken": "*204 characters*",
      "expiresin": "3600",
      "localid": "*28 characters*"
    }

Neither `idtoken` nor `refreshtoken` worked as the value of `token` in your snippet.

**Comment by Overvault-64** [comment]
I added a [function draft](https://github.com/Overvault-64/Firebase-Godot-API/blob/635fdeb029c26cf168536610c7550a4b6b9deee9/addons/FirebaseAPI/realtime/realtime.gd#L24), but as you tested for yourself it doesn't work. I assume the guys maintaining the original API faced similar issues implementing this specific (yet simple) feature and let it go at some point. Don't really know.

You can use "disposable" references as a workaround. Remember to kill them after you stored the initial value to prevent memory leak. I see no real downside to this approach.

**Comment by Overvault-64** [comment]
Added `get_snapshot()` function in `Reference` class. Try it out:

```
func your_func():
	var ref = Firebase.Realtime.get_realtime_reference("path")
	print(await ref.get_snapshot("some_sub_path"))
```
